name: Publish NPM Package

on:
    release:
        types: 
            - published

jobs:
    publish:
        name: Publish Package
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  registry-url: https://registry.npmjs.org
                  scope: '@newfold'
            - uses: fregante/setup-git-user@v2

            - name: Bump Build Version
              run: npm version prerelease

            - name: Install Dependencies
              run: npm ci

            - name: Create Build
              run: npm run build

            - name: Publish Package
              run: npm publish
              working-directory: ./build

