##
# This workflow is used to publish the package to npm. It does the following:
# 1. Checks out the repository/main branch.
# 2. Sets up the node environment with the necessary configuration.
# 3. Installs the dependencies.
# 4. Creates a build of the package.
# 5. Publishes the build to npm.
##
name: Publish NPM Package

on:
    push:
        tags:
            - '*'

jobs:
    publish:
        name: Publish Package
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  token: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
            - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
              with:
                  node-version: 20.x
                  registry-url: https://registry.npmjs.org
                  scope: '@newfold'
            - uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2.0.2

            - name: Install Dependencies
              run: npm install

            - name: Create Build
              run: npm run build

            - name: Publish Package
              run: npm publish
              working-directory: ./build
