##
# This workflow is used to prepare a release of the package. It does the following:
# 1. Checks out the repository/main branch.
# 2. Sets up the node environment.
# 3. Configures the git user.
# 4. Bumps the version of the package to the input version.
# 5. Creates a pull request with the new version.
##
name: Prepare Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: The version level to be used (patch, minor, major).
                type: choice
                default: "patch"
                options:
                    - patch
                    - minor
                    - major
                required: true

jobs:
    prepare-release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          with:
              ref: main
              token: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
        - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
          with:
              node-version: 20.x
        - uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2.0.2

        - name: Configure Git
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        - name: Bump Version
          run: npm version ${{  github.event.inputs.version }} --no-git-tag-version

        - name: Get New Version
          id: get-new-version
          run: |
            VERSION=$(node -p "require('./package.json').version")
            echo "new_version=${VERSION}" >> $GITHUB_OUTPUT

        - name: Create Release
          uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "automated 🤖: bump version to ${{ steps.get-new-version.outputs.new_version }}"
            title: "Automated 🤖: bump version to ${{ steps.get-new-version.outputs.new_version }}"
            body: |
                This PR bumps the package version from the previous version to `${{ steps.get-new-version.outputs.new_version }}`.

                - Updated `package.json` version
                - Updated `package-lock.json` version

                ---
                *This PR was created automatically by the Prepare Release workflow.*
            branch: release/${{ steps.get-new-version.outputs.new_version }}
