name: Commit Version Bump

on:
    workflow_run:
      workflows: [Publish NPM Package]
      types:
        - completed

jobs:
    bump-version:
        name: Version Bump
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: main
                  token: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - uses: fregante/setup-git-user@v2

            - name: Commit Bump
              run: npm version prerelease -m "Bump version to %s"
            
            - name: Push Changes
              run: git push
        
    on-failure:
        name: Version Bump Failure
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:    
            - run: echo "Failed to bump version. Check triggering workflow for errors."
            - run: exit 1
